# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cityTemperature.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1217, 822)
        self.City_label = QtWidgets.QLabel(Form)
        self.City_label.setGeometry(QtCore.QRect(110, 10, 58, 16))
        self.City_label.setObjectName("City_label")
        self.alpha_button = QtWidgets.QPushButton(Form)
        self.alpha_button.setGeometry(QtCore.QRect(230, 40, 171, 51))
        self.alpha_button.setObjectName("alpha_button")
        self.reverse_button = QtWidgets.QPushButton(Form)
        self.reverse_button.setGeometry(QtCore.QRect(230, 180, 171, 51))
        self.reverse_button.setObjectName("reverse_button")
        self.city_info_text = QtWidgets.QTextBrowser(Form)
        self.city_info_text.setGeometry(QtCore.QRect(60, 280, 311, 191))
        self.city_info_text.setObjectName("city_info_text")
        self.city_list = QtWidgets.QListView(Form)
        self.city_list.setGeometry(QtCore.QRect(60, 40, 161, 192))
        self.city_list.setObjectName("city_list")
        self.Information_label = QtWidgets.QLabel(Form)
        self.Information_label.setGeometry(QtCore.QRect(170, 250, 101, 16))
        self.Information_label.setObjectName("Information_label")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(60, 480, 181, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 279))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(150, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout.addWidget(self.checkBox_14)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.threshold_line = QtWidgets.QLineEdit(Form)
        self.threshold_line.setGeometry(QtCore.QRect(260, 550, 113, 21))
        self.threshold_line.setObjectName("threshold_line")
        self.Threshold_label = QtWidgets.QLabel(Form)
        self.Threshold_label.setGeometry(QtCore.QRect(280, 520, 71, 16))
        self.Threshold_label.setObjectName("Threshold_label")
        self.Plot_button = QtWidgets.QPushButton(Form)
        self.Plot_button.setGeometry(QtCore.QRect(260, 600, 112, 32))
        self.Plot_button.setObjectName("Plot_button")
        self.graphics_View = QtWidgets.QGraphicsView(Form)
        self.graphics_View.setGeometry(QtCore.QRect(400, 40, 791, 761))
        self.graphics_View.setObjectName("graphics_View")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(660, 20, 111, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.City_label.setText(_translate("Form", "City List"))
        self.alpha_button.setText(_translate("Form", "alphabetically"))
        self.reverse_button.setText(_translate("Form", "Reverse alphabetically"))
        self.Information_label.setText(_translate("Form", "City information"))
        self.checkBox_1.setText(_translate("Form", "Boston"))
        self.checkBox_2.setText(_translate("Form", "Chicago"))
        self.checkBox_3.setText(_translate("Form", "Houston"))
        self.checkBox_4.setText(_translate("Form", "Las Vegas"))
        self.checkBox_5.setText(_translate("Form", "Los Angeles"))
        self.checkBox_6.setText(_translate("Form", "Miami"))
        self.checkBox_7.setText(_translate("Form", "Minneapolis"))
        self.checkBox_8.setText(_translate("Form", "New York"))
        self.checkBox_9.setText(_translate("Form", "Philadelphia"))
        self.checkBox_10.setText(_translate("Form", "San Antonio"))
        self.checkBox_11.setText(_translate("Form", "San Diego"))
        self.checkBox_12.setText(_translate("Form", "San Francisco"))
        self.checkBox_13.setText(_translate("Form", "Seattle"))
        self.checkBox_14.setText(_translate("Form", "Washington D.C."))
        self.Threshold_label.setText(_translate("Form", "Threshold:"))
        self.Plot_button.setText(_translate("Form", "Plot"))
        self.label.setText(_translate("Form", "Graphics Analysis"))
